### ISSUE TITLE
Foreman HDM does not build on latest foreman version

### ISSUE THREAD

**Issue by tuxmea** [betadots/foreman_hdm#26]
Build log: https://download.copr.fedorainfracloud.org/results/@theforeman/plugins-nightly-staging-scratch-9f524913-0e80-5852-9375-9969205e107e/rhel-8-x86_64/06975676-rubygem-foreman_hdm/builder-live.log.gz

```text
 WARN  app : You are trying to replace import_subnets from . Adding allowed actions from plugin permissions to the existing one.
rake aborted!
ArgumentError: wrong number of arguments (given 1, expected 2)
/builddir/build/BUILD/foreman_hdm-0.1.4/usr/share/foreman/app/models/concerns/belongs_to_proxies.rb:17:in `register_smart_proxy'
/builddir/build/BUILD/foreman_hdm-0.1.4/usr/share/foreman/app/models/host.rb:43:in `method_missing'
/builddir/build/BUILD/foreman_hdm-0.1.4/usr/share/foreman/app/registries/foreman/plugin.rb:509:in `smart_proxy_for'
/builddir/build/BUILDROOT/rubygem-foreman_hdm-0.1.4-2.fm3_10.el8.x86_64/usr/share/gems/gems/foreman_hdm-0.1.4/lib/foreman_hdm/engine.rb:34:in `block (2 levels) in <class:Engine>'
/builddir/build/BUILD/foreman_hdm-0.1.4/usr/share/foreman/app/registries/foreman/plugin.rb:100:in `instance_eval'
/builddir/build/BUILD/foreman_hdm-0.1.4/usr/share/foreman/app/registries/foreman/plugin.rb:100:in `register'
/builddir/build/BUILDROOT/rubygem-foreman_hdm-0.1.4-2.fm3_10.el8.x86_64/usr/share/gems/gems/foreman_hdm-0.1.4/lib/foreman_hdm/engine.rb:20:in `block in <class:Engine>'
/usr/share/gems/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `instance_exec'
/usr/share/gems/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `run'
/builddir/build/BUILD/foreman_hdm-0.1.4/usr/share/foreman/config/initializers/0_print_time_spent.rb:45:in `block in run'
/builddir/build/BUILD/foreman_hdm-0.1.4/usr/share/foreman/config/initializers/0_print_time_spent.rb:17:in `benchmark'
/builddir/build/BUILD/foreman_hdm-0.1.4/usr/share/foreman/config/initializers/0_print_time_spent.rb:45:in `run'
/usr/share/gems/gems/railties-6.1.7.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/share/ruby/tsort.rb:228:in `block in tsort_each'
/usr/share/ruby/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/share/ruby/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/share/ruby/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/share/ruby/tsort.rb:347:in `each'
/usr/share/ruby/tsort.rb:347:in `call'
/usr/share/ruby/tsort.rb:347:in `each_strongly_connected_component'
/usr/share/ruby/tsort.rb:226:in `tsort_each'
/usr/share/ruby/tsort.rb:205:in `tsort_each'
/usr/share/gems/gems/railties-6.1.7.6/lib/rails/initializable.rb:60:in `run_initializers'
/usr/share/gems/gems/railties-6.1.7.6/lib/rails/application.rb:391:in `initialize!'
/usr/share/gems/gems/railties-6.1.7.6/lib/rails/railtie.rb:207:in `public_send'
/usr/share/gems/gems/railties-6.1.7.6/lib/rails/railtie.rb:207:in `method_missing'
/builddir/build/BUILD/foreman_hdm-0.1.4/usr/share/foreman/config/environment.rb:5:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
/usr/share/gems/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/usr/share/gems/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/share/gems/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/share/gems/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `require'
/usr/share/gems/gems/railties-6.1.7.6/lib/rails/application.rb:367:in `require_environment!'
/usr/share/gems/gems/railties-6.1.7.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/share/gems/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/share/gems/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/usr/share/gems/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/bin/rake:23:in `load'
/usr/bin/rake:23:in `<main>'
Tasks: TOP => plugin:assets:precompile => environment
```

**Comment by tuxmea** [comment]
https://github.com/theforeman/foreman/pull/10006 caused it

https://github.com/theforeman/foreman-packaging/pull/10374 has further analysis
